main: com.weebly.openboxtechnologies.hnrperms.Main
name: BukkitTemplate
version: 0.1
author: TechnoBrony
description: Bukkit Template
commands:
   templatecmd:
      description: This is a demo command.
      usage: /<command>
      permission: <plugin name>.templatecmd
      permission-message: Sorry, you can't run this command.