main: com.weebly.openboxtechnologies.hnrperms.hnrperms
name: HnRPerms
version: 0.2
author: TechnoBrony
description: HnRPerms Plugin
commands:
   hnrperms:
      description: Main command of the HnR Permissions System.
      usage: /<command>