main: com.weebly.openboxtechnologies.hnrperms.Main
name: HnRPerms
version: 0.1
author: TechnoBrony
description: HnRPerms Plugin
commands:
   hnrperms:
      description: Main command of the HnR Permissions System.
      usage: /<command>